version: '3.8'
name: mongo

services:
  mongodb:
    image: mongo:latest
    container_name: test_parsers.mongodb
    env_file:
      - ../.env
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_DATABASE=${MONGO_DB}"
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}"
    volumes:
      - ../data/db:/data/db
    command:
      mongod --quiet --logpath /dev/null
    networks:
      - backend

#volumes:
#  ../data/db:

networks:
  backend:
    driver: bridge