version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: euronews.mongodb
    env_file:
      - ../.env
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      - "MONGO_INITDB_DATABASE=${MONGO_DB}"
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}"
    volumes:
      - dbdata:/data/db
    command:
      mongod --quiet --logpath /dev/null
    networks:
      - backend

  mongo-express:
    image: mongo-express
    container_name: euronews.mongo-express
    restart: always
    env_file:
      - ../.env
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASS}@${MONGO_HOST}:${MONGO_PORT}/
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_AUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_AUTH_PASSWORD}
    depends_on:
      - mongodb
    networks:
      - backend

volumes:
  dbdata:

networks:
  backend:
    driver: bridge