services:

  fastapi:
    build: .
    env_file:
      - .env
    volumes:
      - /root/parsers:/app
    ports:
      - "1111:8000"
    depends_on:
      - mongodb
    restart: unless-stopped
    container_name: test_parsers.fastapi
    command: bash -c 
      "uvicorn --factory api.backend.main:create_app --host 0.0.0.0 --port 8000 --lifespan=on --use-colors --reload"
    networks:
      - custom

  mongodb:
    image: mongo:latest
    container_name: test_parsers.mongodb
    env_file:
      - .env
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}"
    volumes:
      - /root/parsers/data/db:/data/db
    command:
      mongod --quiet --logpath /dev/null
    networks:
      - backend

networks:
  backend:
    driver: bridge
